import { PLAYBOOK_SOURCE_LABEL, PLAYBOOK_SOURCES, RULE_META } from './meta.js';

/**
 * Markdown rendering of the rule playbooks for docs/08-FINDINGS.md. The
 * registry in `meta.ts` is the single source: the block between the
 * markers is generated by `pnpm docs:playbooks` and a drift test keeps the
 * committed docs equal to what the registry renders, the same way the JSON
 * schema is generated from the zod source and checked in CI.
 */

export const PLAYBOOKS_START = '<!-- playbooks:start -->';
export const PLAYBOOKS_END = '<!-- playbooks:end -->';

/** The generated block, markers excluded, LF line endings, trailing newline. */
export function renderPlaybooksMarkdown(): string {
  const out: string[] = [
    '<!-- Generated from RULE_META in packages/core/src/insights/meta.ts by `pnpm docs:playbooks`. Edit the registry, not this block. -->',
  ];
  for (const [id, meta] of Object.entries(RULE_META)) {
    const { causes, actions, limits } = meta.playbook;
    out.push('', `### \`${id}\` · ${meta.label}`, '', meta.explain, '');
    out.push('**Why it happens**', '');
    for (const cause of causes) out.push(`- ${cause}`);
    out.push('', '**What you can do**');
    for (const source of PLAYBOOK_SOURCES) {
      out.push('', `*${PLAYBOOK_SOURCE_LABEL[source]}*`, '');
      for (const action of actions[source]) out.push(`- ${action}`);
    }
    out.push('', '**Out of your hands**', '');
    for (const limit of limits) out.push(`- ${limit}`);
  }
  return `${out.join('\n')}\n`;
}

/** The current block between two markers, markers excluded; undefined when
 * they are missing. Line endings are normalized to LF. */
export function extractBlock(
  doc: string,
  startMarker: string,
  endMarker: string,
): string | undefined {
  const text = doc.replace(/\r\n/g, '\n');
  const start = text.indexOf(startMarker);
  const end = text.indexOf(endMarker);
  if (start < 0 || end < 0 || end < start) return undefined;
  return text.slice(start + startMarker.length, end).replace(/^\n/, '');
}

/** The document with the block between two markers replaced; throws when
 * the markers are missing. */
export function replaceBlock(
  doc: string,
  startMarker: string,
  endMarker: string,
  block: string,
): string {
  const text = doc.replace(/\r\n/g, '\n');
  const start = text.indexOf(startMarker);
  const end = text.indexOf(endMarker);
  if (start < 0 || end < 0 || end < start) {
    throw new Error(`markers ${startMarker} … ${endMarker} not found`);
  }
  return `${text.slice(0, start + startMarker.length)}\n${block}${text.slice(end)}`;
}

/** The current playbooks block of a document (see `extractBlock`). */
export function extractPlaybooksBlock(doc: string): string | undefined {
  return extractBlock(doc, PLAYBOOKS_START, PLAYBOOKS_END);
}

/** The document with its playbooks block replaced (see `replaceBlock`). */
export function replacePlaybooksBlock(doc: string, block: string): string {
  return replaceBlock(doc, PLAYBOOKS_START, PLAYBOOKS_END, block);
}
