/**
 * build-pricing-snapshot.ts — regenerates the bundled pricing snapshot from
 * LiteLLM's public price list (05-ARCHITECTURE §2.3).
 *
 * This is a DEV/BUILD-TIME script: the product itself performs no network
 * calls at runtime (AGENTS.md) — the snapshot ships inside @runray/core as
 * a generated TypeScript module. Re-run to refresh prices:
 *
 *   pnpm pricing:snapshot
 *
 * Output: packages/core/src/pricing/snapshot.ts (committed, generated).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  MODEL_TIERS,
  matchModel,
} from '../packages/core/src/pricing/engine.js';
import {
  DEFAULT_PRICING_PROVIDERS,
  LITELLM_PRICING_URL,
  priceListFromText,
} from '../packages/core/src/pricing/litellm.js';
import { BUNDLED_PRICING } from '../packages/core/src/pricing/snapshot.js';

const res = await fetch(LITELLM_PRICING_URL, {
  signal: AbortSignal.timeout(5 * 60_000),
});
if (!res.ok) throw new Error(`fetch failed: ${res.status} ${res.statusText}`);

// Same checks as `runray pricing --refresh`: a list under half the current
// snapshot is refused as truncated, since a tiny snapshot would also lower
// the bar for every user refresh. Pass --allow-short-list to accept it.
const snapshotDate = new Date().toISOString().slice(0, 10);
const table = priceListFromText(await res.text(), {
  snapshotDate,
  minEntries: process.argv.includes('--allow-short-list')
    ? 1
    : Math.ceil(BUNDLED_PRICING.entries.length / 2),
  onInvalid: (key, problem) =>
    console.warn(`warning: left out ${key}: ${problem}`),
});

// tier-ladder targets must stay resolvable, or suggestedDowngrade degrades
// to "no suggestion" — surface it at refresh time, not at a user's runtime
for (const stages of MODEL_TIERS) {
  for (const stage of stages) {
    const entry = matchModel(table, stage.target);
    if (entry === undefined) {
      console.warn(
        `warning: MODEL_TIERS target "${stage.target}" (${stage.id}) no longer resolves in the refreshed snapshot — update the ladder in packages/core/src/pricing/engine.ts`,
      );
    } else if (entry.inputPerMTok <= 0 || entry.outputPerMTok <= 0) {
      console.warn(
        `warning: MODEL_TIERS target "${stage.target}" (${stage.id}) has zero base rates in the refreshed snapshot`,
      );
    }
  }
}

const target = fileURLToPath(
  new URL('../packages/core/src/pricing/snapshot.ts', import.meta.url),
);
const content = `// GENERATED by scripts/build-pricing-snapshot.ts — DO NOT EDIT BY HAND.
// Source: LiteLLM model_prices_and_context_window.json (providers: ${[...DEFAULT_PRICING_PROVIDERS].sort().join(', ')}).
// Refresh with: pnpm pricing:snapshot
import type { PricingTable } from './engine.js';

export const BUNDLED_PRICING: PricingTable = {
  snapshotDate: '${table.snapshotDate}',
  source: 'litellm-snapshot',
  aliases: {},
  entries: ${JSON.stringify(table.entries, null, 2)
    .replace(/"([a-zA-Z][a-zA-Z0-9]*)":/g, '$1:')
    .replace(/"/g, "'")},
};
`;
writeFileSync(target, content, 'utf8');
console.log(
  `wrote ${target} (${table.entries.length} entries, snapshot ${table.snapshotDate})`,
);
